baseURL = "https://lkummer.github.io/Lander/"
title = "Lander"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "Lander"
    text = "Hugo theme for landing and documentation sites."
  [params.seo]
    description = "Customizable Hugo theme for landing and documentation sites. Create beautiful documentation with ease."
    category = "Hugo Theme"
    downloadURL = "https://github.com/LKummer/Lander/releases"
    # When the versionEnv option is set, the version is picked up from the
    # specified environment variable. 
    versionEnv = "npm_package_version"
    # The version can also be specified manually:
    # version = "0.1.0"
    operatingSystem = "Any"
    isFree = true
    license = "https://github.com/LKummer/Lander/blob/master/license.md"
    defaultAuthor = "Lander Contributors"
  [params.graphics]
    logo = """
    <svg class="navbar-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
      <defs>
        <style>
          .navbar {
            --logo-rotation: 0deg;
            --logo-color: var(--color-primary-600);
          }
          .logo-fill {
            fill: var(--logo-color);
            transform-origin: 24px 24px;
            transform: rotate(var(--logo-rotation));
            transition: fill 0.25s ease, transform 0.25s ease;
          }
          .navbar-logo-link:hover {
            --logo-color: var(--color-accent-400);
            --logo-rotation: 60deg;
          }
        </style>
      </defs>
      <path class="logo-fill" d="M42.2,11.7C42.2,11.7,42.2,11.7,42.2,11.7C38.5,6.2,32.4,2.5,25.3,2h0c-2.4,1-5.8,2.6-10.4,5.3
        c-5.1,3-8.5,5.3-10.7,7.1C2.8,17.3,2,20.5,2,24c0,3.5,0.8,6.9,2.3,9.8c2.1,1.6,5.1,3.7,9.8,6.4c5.1,2.9,8.9,4.7,11.5,5.7
        c7-0.5,13.1-4.3,16.8-9.8c0,0,0,0,0,0c0.4-2.6,0.6-6.3,0.6-11.6C43,18.6,42.6,14.5,42.2,11.7z M24,37c-7.2,0-13-5.8-13-13
        s5.8-13,13-13s13,5.8,13,13S31.2,37,24,37z"/>
    </svg>
    """
    favicon = "favicon.svg"

[menu]
  [[menu.main]]
    name = "Download"
    url = "https://github.com/LKummer/Lander/releases"
  [[menu.footer]]
    name = "Download"
    url = "https://github.com/LKummer/Lander/releases"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
