baseURL = "https://lkummer.github.io/Lander/"
title = "Lander"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "Lander"
    text = "Hugo theme for landing and documentation sites."
  [params.seo]
    description = "Customizable Hugo theme for landing and documentation sites. Create beautiful documentation with ease."
    category = "Hugo Theme"
    downloadURL = "https://github.com/LKummer/Lander/releases"
    # When the versionEnv option is set, the version is picked up from the
    # specified environment variable. 
    versionEnv = "npm_package_version"
    # The version can also be specified manually:
    # version = "0.1.0"
    operatingSystem = "Any"
    isFree = true
    license = "https://github.com/LKummer/Lander/blob/master/license.md"
    defaultAuthor = "Lander Contributors"

[menu]
  [[menu.main]]
    name = "Download"
    url = "https://github.com/LKummer/Lander/releases"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
