baseURL = "https://lkummer.github.io/Lander/demo"
title = "Lander"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "theme"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "Footer Title"
    text = "Footer section text."
  [params.seo]
    category = "Hugo Theme"
    downloadURL = "#"
    # When the versionEnv option is set, the version is picked up from the
    # specified environment variable. 
    versionEnv = "npm_package_version"
    # The version can also be specified manually:
    # version = "0.1.0"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Lander Contributors"

[menu]
  [[menu.main]]
    name = "Download"
    url = "#"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
