baseURL = "https://lkummer.github.io/Lander/demo/"
title = "Lander Demo"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "About"
    text = """
    This is a demo for the Lander Hugo theme.
    See the Lander documentation to learn more.
    """
  [params.seo]
    description = "Description of the site."
    category = "Hugo Theme"
    downloadURL = "#"
    # When the versionEnv option is set, the version is picked up from the
    # specified environment variable. 
    versionEnv = "npm_package_version"
    # The version can also be specified manually:
    # version = "0.1.0"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Lander Contributors"
  [params.colors]
    primary-600 = "hsl(216, 40%, 32%)"
    primary-500 = "hsl(216, 45%, 35%)"
    primary-400 = "hsl(216, 55%, 40%)"
    accent-600 = "hsl(27, 95%, 38%)"
    accent-500 = "hsl(27, 90%, 42%)"
    accent-400 = "hsl(27, 80%, 50%)"
    accent-300 = "hsl(216, 27%, 65%)"
    accent-200 = "hsl(216, 25%, 67%)"
    accent-100 = "hsl(216, 20%, 70%)"
    background-900 = "hsl(216, 40%, 20%)"
    background-400 = "hsl(216, 10%, 90%)"
    background-300 = "hsl(216, 10%, 92%)"
    background-200 = "hsl(216, 10%, 95%)"
    background-100 = "hsl(216, 10%, 97%)"
    text-900 = "hsla(0, 0%, 0%, 0.75)"
    text-800 = "hsla(0, 0%, 0%, 0.7)"
    text-700 = "hsla(0, 0%, 0%, 0.55)"
    text-100 = "hsla(0, 0%, 100%, 0.9)"
    highlight-inline = "hsl(27, 80%, 50%)"
    highlight-text = "hsl(240, 35%, 99%)"
    highlight-background = "hsl(240, 13%, 14%)"
    highlight-comment = "hsl(250, 25%, 55%)"
    highlight-special = "hsl(180, 75%, 55%)"
    highlight-operator = "hsl(330, 95%, 75%)"
    highlight-literal = "hsl(250, 80%, 70%)"
  [params.graphics]
    logo = """
    <svg class="navbar-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
      <defs>
        <style>
          :root {
            --logo-rotation: 0deg;
          }
          .logo-fill {
            fill: var(--color-primary-600);
            transform-origin: 24px 24px;
            transform: rotate(var(--logo-rotation));
            transition: fill 0.25s, transform 0.25s ease;
          }
          .navbar-logo-link:hover {
            --color-primary-600: var(--color-primary-400);
            --logo-rotation: 60deg;
          }
        </style>
      </defs>
      <path class="logo-fill" d="M42.2,11.7C42.2,11.7,42.2,11.7,42.2,11.7C38.5,6.2,32.4,2.5,25.3,2h0c-2.4,1-5.8,2.6-10.4,5.3
        c-5.1,3-8.5,5.3-10.7,7.1C2.8,17.3,2,20.5,2,24c0,3.5,0.8,6.9,2.3,9.8c2.1,1.6,5.1,3.7,9.8,6.4c5.1,2.9,8.9,4.7,11.5,5.7
        c7-0.5,13.1-4.3,16.8-9.8c0,0,0,0,0,0c0.4-2.6,0.6-6.3,0.6-11.6C43,18.6,42.6,14.5,42.2,11.7z M24,37c-7.2,0-13-5.8-13-13
        s5.8-13,13-13s13,5.8,13,13S31.2,37,24,37z"/>
    </svg>
    """

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
