name: Deliver

on:
  push:
    tags:
      - 'v*'

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build the Theme
        run: npm run theme:build:prod
      
      - name: Rename the Theme
        run: mkdir dist/archive && mv dist/theme dist/archive/lander

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip the Theme
        run: 7z a -tzip dist/lander.zip dist/archive
      
      - name: Upload Zipped Theme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/lander.zip
          asset_name: lander_${{ steps.create-release.outputs.id }}.zip
          asset_content_type: application/zip

      - name: Archive and Compress the Theme
        run: tar -czf dist/lander.tar.gz dist/archive
        
      - name: Upload Archived and Compressed Theme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/lander.tar.gz
          asset_name: lander_${{ steps.create-release.outputs.id }}.tar.gz
          asset_content_type: application/gzip
