name: Deliver

on:
  push:
    tags:
      - 'v*'

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build the Theme
        run: npm run theme:build:prod
      
      - name: Rename the Theme
        run: mv dist/theme dist/lander

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip the Theme
        run: cd dist && 7z a -tzip lander.zip lander
      
      - name: Upload Zipped Theme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/lander.zip
          asset_name: lander.zip
          asset_content_type: application/zip

      - name: Archive and Compress the Theme
        run: cd dist && tar -czf lander.tar.gz lander
        
      - name: Upload Archived and Compressed Theme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/lander.tar.gz
          asset_name: lander.tar.gz
          asset_content_type: application/gzip
      
      - name: Copy Theme to Demo Site
        run: mkdir demo/themes && cp -r dist/lander demo/themes

      - name: Zip the Demo Site
        run: cd demo && 7z a -tzip ../dist/quickstart-site.zip .
      
      - name: Upload Zipped Demo
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/quickstart-site.zip
          asset_name: quickstart-site.zip
          asset_content_type: application/zip
      
      - name: Archive and Compress the Demo Site
        run: cd demo && tar -czf ../dist/quickstart-site.tar.gz **/* *
        
      - name: Upload Archived and Compressed Demo Site
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/quickstart-site.tar.gz
          asset_name: quickstart-site.tar.gz
          asset_content_type: application/gzip
