name: Lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: node-version: 12.x

      - name: Install Dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint:js

      - name: Lint Style
        run: npm run lint:style
